Default: &defaults
  database: Tabeyou.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Tabeyou_test.sqlite3
  <<: *defaults

Staging:
  database: Tabeyou_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: Tabeyou_production.sqlite3
  poolsize: 100
  <<: *defaults
